### ISSUE TITLE
Looking forward to this plugin, but fatal error

### ISSUE THREAD

**Issue by martk70** [mizunashi-mana/dokuwiki-plugin-mdpage#16]
With some markdown, (between  the plugin tags) this is what I get:

Catchable fatal error: Argument 2 passed to syntax_plugin_mdpage::renderWithRenderer() must be an instance of string, string given, called in /var/www/html/qportal/lib/plugins/mdpage/syntax.php on line 56 and defined in /var/www/html/qportal/lib/plugins/mdpage/syntax.php on line 59

**Comment by mizunashi-mana** [comment]
@martk70 Thanks for reporting!  I will fix this bug and release next version soon.

**Comment by mizunashi-mana** [comment]
@martk70 I released new version.  Please update this plugin.  If you will get same error yet, please reopen this issue.
