### ISSUE TITLE
Links with title broken

### ISSUE THREAD

**Issue by brzGatsu** [mizunashi-mana/dokuwiki-plugin-mdpage#35]
DokuWiki 2018.04.22-0122
Apache 2.2.34-0020
PHP 7.0.30-0027

Links with title seem to be broken:

```[I'm an inline-style link with title](https://www.google.com "Google's Homepage")```

**Comment by mizunashi-mana** [comment]
See also: https://github.com/splitbrain/dokuwiki/issues/2573

**Comment by mizunashi-mana** [comment]
Thanks for many voting. Now, this plugin supports links with titles. Please upgrade plugins.
