### ISSUE TITLE
Use pictures from DokuWiki inside Markdown Blocks

### ISSUE THREAD

**Issue by KiraResari** [mizunashi-mana/dokuwiki-plugin-mdpage#44]
**This is a feature request.**

Specification:
This is a very specific request. I would like to have a way to use pictures that were uploaded to the DokuWiki inside markdown elements, so they can be used within markdown language.

Minimalistic example:
```
<markdown>
{{ images:start_page.png?direct&960|Start Page }}
</markdown>
```

Motivations:
Currently, whenever I want to use pictures uploaded to DokuWiki anywhere within the markdown block, I have to provide a direct link to the picture, which I first have to generate by inserting the picture outside the markdown block and then copying the link. The alternative would be to break the markdown block every time I need to insert a picture, but that would be impossible once the picture is embedded in any markdown elements.

Current workaround:
```
<markdown>
![Start Page](https://wiki.company.de/lib/exe/fetch.php?w=960&tok=3307a0&media=images:start_page_german.png)
</markdown>
```

**Comment by mizunashi-mana** [comment]
@KiraResari Hi, thanks for the request!

I released new version including internal media support.
Please, update plugins!
