### ISSUE TITLE
Use DokuWiki Links inside Markdown Blocks

### ISSUE THREAD

**Issue by KiraResari** [mizunashi-mana/dokuwiki-plugin-mdpage#45]
**This is a feature request.**

Specification:
I would like to see a way to integrate DokuWiki links into the markdown blocks, for example:

```
<markdown>
[[documentation:website:pages:start_page|Start Page]]
<markdown>
```

Motivations:
Currently, I can't find a way to do that, and the alternative of typing the full html link in the default markdown format has the drawback that it is treated as an external link by DokuWiki, and also causes trouble if pages are renamed.

Current Workaround:
```
<markdown>
[Start Page](https://wiki.company.de/doku.php?id=documentation:website:pages:start_page)
<markdown>
```

**Comment by mizunashi-mana** [comment]
@KiraResari Hi, thanks for the request!

I released new version including internal link support.
Please, update plugins!
