### ISSUE TITLE
Double HTML escaping

### ISSUE THREAD

**Issue by NeoEGM** [mizunashi-mana/dokuwiki-plugin-mdpage#50]
**This is a bug report.**

| Name | Value |
| --- | --- |
| DokuWiki Version | Release 2018-04-22b "Greebo" |
| PHP Version | 7.3.10 |
| OS | Linux |
| Web Server | Apache/2.4.41 (Unix) OpenSSL/1.1.0l PHP/7.3.10 |
| Docker image | bitnami/dokuwiki |

Details:

Given the following simple page code:

```gfm
<markdown>
# Test 1, Test 2 & More tests

This is text
</markdown>
```

Instead of the expected heading:

```plaintext
Test 1, Test 2 & More tests
```

It renders:

```plaintext
Test 1, Test 2 &amp; More tests
```

I didn't have time to dive into the code to fix it. I tried the plugin today for the first time.

Tell me if you need any more info or any help.

Thanks!

**Comment by mizunashi-mana** [comment]
By #54

**Comment by mizunashi-mana** [comment]
Thanks for report!  I worked it and released new version.  Please update the plugin.

**Comment by NeoEGM** [comment]
Thanks!! I'll install it!
