### ISSUE TITLE
markdown plugins conflicts with ckgedit but is not mentioned as a conflicting plugin

### ISSUE THREAD

**Issue by gilsedawk** [mizunashi-mana/dokuwiki-plugin-mdpage#52]
Hi, your markdown plugin conflicts with ckgedit plugin but it is not mentioned as a conflicting plugin.

please fix this or mention in the documentation that there is a conflict between the two.

thank you

**Comment by mizunashi-mana** [comment]
@gilsedawk Thanks for your report.

I wonder why.  Could you provide any samples for my understanding?  I would fix this issue as possible.

**Comment by gilsedawk** [comment]
Hi,

yes,
for example:
when you create an (un)ordered list with markdown
and press save the list is scrambled.

if you have a code block then de end code tag becoms visible.

When disabeling the ckgedit plugin this problem does not occur.

So it easy to spot it goes wrong when both plugins are enabled.

I think the ckgedit bplugin is very much used and we have to disable it now because of the conflict.

I would be really happy if you can look into it.

thx!

**Comment by mizunashi-mana** [comment]
@gilsedawk Hmm...

This plugin allow markdown syntax only in markdown block. I cannot confirm this issue to play lightly. Maybe, you use markdownku plugin or any other plugins instead by this plugin (mdpage plugin)?

Or, means it is different from your expectation that

```
<markdown>
* aaa
* bbb
</markdown>
```

is rendered

```
<markdown>

* aaa

* bbb

</markdown>
```

with GUI mode?

**Comment by gilsedawk** [comment]
yes its mdpage, and no other markdown plugins.

i just tried your example and after saving it becomes:

''<markdown>
* aaa
* bbb
</markdown>''

so it looks like a code block in the saved webpage :(

i don't think i can upload a screenshot here?

**Comment by gilsedawk** [comment]
![mdpage](https://user-images.githubusercontent.com/56582008/69965572-d11ba300-1514-11ea-88a4-6ba7fb3d5fed.png)

**Comment by mizunashi-mana** [comment]
I have very poor knowledge about ckgedit .  I show the steps I tried:

1. Install ckgedit and mdpage plugin to my DokuWiki
2. Then, create new page with GUI mode:

    ![スクリーンショット 2019-12-02 23 17 28](https://user-images.githubusercontent.com/11599514/69966539-f7affd00-1559-11ea-9e22-eff02716e8de.png)

3. I wrote the example:

    ![スクリーンショット 2019-12-02 23 18 41](https://user-images.githubusercontent.com/11599514/69966625-25954180-155a-11ea-97e7-6a07b4990c96.png)

4. Click save button, and then I saw:

    ![スクリーンショット 2019-12-02 23 19 35](https://user-images.githubusercontent.com/11599514/69966681-4067b600-155a-11ea-9396-c329a026bc18.png)

Are these steps wrong?  How can I fix these?

**Comment by gilsedawk** [comment]
no thats exactly what i do.

if i do not install ckgedit it works as you show here in your images.

if i enable ckgedit i get the code block like in my image.

very strange...
maybe it is a combination of more than 2 plugins.

i will try and find out.

**Comment by mizunashi-mana** [comment]
I close this to keep critical issues clear.  If you are keeping this issue yet, you always can reopen.
