### ISSUE TITLE
Ampersand characters being converted to &amp; and rendered as &amp;

### ISSUE THREAD

**Issue by devaneando** [mizunashi-mana/dokuwiki-plugin-mdpage#53]
**This is a bug report.**

| Name | Value |
| --- | --- |
| DokuWiki Version |Release 2018-04-22b "Greebo" |
| PHP Version |PHP 7.3.17 |
| OS |Linux Mint 19.3 Cinnamon |
| Web Server |Apache2 |

Details:

The ampersand character is being converted to the html entity and being displayed as &amp;

For example, the page below

```
<markdown>
# Install Docker & Docker-compose
</markdown>
```

Will be rendered as `Install Docker &amp; Docker-compose`

The correct rende would be **Install Docker & Docker-compose**

**NOTE**

This behavior seems to happen only in titles.

In normal text, the & works as expected.

**Comment by mizunashi-mana** [comment]
Thanks for report!  I worked it and released new version.  Please update the plugin.
