### ISSUE TITLE
Option for Markdown mode being always active?

### ISSUE THREAD

**Issue by jasonfharris** [mizunashi-mana/dokuwiki-plugin-mdpage#60]
**This is a feature request.**

Specification: Can one enable it so that one dose not need to prefix all markdown content with `<markdown>`? As I understand it every page need to begin with `<markdown>` and end with `</markdown>`

Motivations: I currently use the markdowku plugin and basically all of several hundred pages don't have this prefix / suffix embedded into every page. In fact we basically use the dokuwiki wiki as a markdown wiki and don't use dokuwiki syntax. I could process all the pages I guess with automated search and replace tool, etc. But it would be nice to just have the markdown mode always active. Would this be possible?

**Comment by mizunashi-mana** [comment]
Thanks for the idea.  This option is great.

This plugin's approach to parse is different from markdowku's one.  You can mix Markdown and DokuWiki (i.e. other plugin specified) syntax to write pages with markdowku but cannot with this plugin.  If your pages include some features of other plugins, they are not rendering well with this plugin.

In other words, it is easy that

> it would be nice to just have the markdown mode always active. Would this be possible?

.  However, if you hope to run well for mixed content with Markdown and DokuWiki plugin's syntax, it will be hard work.

I guess adding prefix is not hard work but suffix is obstruction, which kept in your eyes during editing.  Now, this plugin require the suffix correspond to the prefix, but I can remove this requirement.  And, I can provide new prefix which seems a html comment (i.e. `<!-- doctype: markdown -->`); this feature help copying and pasting as pure markdown content.  Then, you will be able to mix Markdown and DokuWiki syntax by using explicit suffix if necessary.

Is the above alternative satisfied your needs?

**Comment by jasonfharris** [comment]
Well... there are a lot of files out there which are just plain markdown files. It is really convenient to just drag them into the pages directory of dokuwiki and you are done! (You likely need to change suffixes from .md to .txt, but still pretty easy) Ie if I have a folder of such files you can just drag them straight into the relent section of the pages dir, and it just works... For a lot of people they will just use markdown for pretty much everything. I know it might sound kind of mean but just like git vs mercurial, markdown has won the mark up battle. Having to remember twiki, dokuwiki, MediaWiki, JIRA markup, etc. etc. Is a real pain. Moreover it is just... well... outmoded. (If you need fine control one is likely to go to HTML / inline CSS anyway...). But that is why I suggested an option. Some people are going to be mixing in markdown with dokuwiki, and I think a substantial fraction of people will just use all markdown. So having an option to just "switch this on" (I am not suggesting it is the default) would be very nice... But in any case thanks for reading the comment and responding to the bug report!

**Comment by mizunashi-mana** [comment]
@jasonfharris OK, I will add the switch which makes DokuWiki syntax as plain Markdown.

Memo for me: Some HTML tags help to embed DokuWiki syntax into plain Markdown:

Idea 1.

```
# Header

<script type="text/x-dokuwiki">
**bold**, //italic//, __underlined__, ''code'' 
</script>
```

**Comment by jasonfharris** [comment]
Thanks! That is awesome! Of course it is just a suggestion :) And I know I would use it and I think a lot of others would use it, but in any case, thanks!

**Comment by mizunashi-mana** [comment]
I just released with new switch.  Please update and use it.
